// Data transforms apply after messageParser & niddabotData and allow pre-processing runtime transformations.

// An example is the argument --delegate=discordId which will substitute the instigating user and run the command as the provided user instead.
// This is, naturally, only usable by Admin rank and above. Substitution can also not target Super Users. This command will make the processing time significantly longer as it will
// have to load the user to verify the rank of the instigating user and then discard it and replace it with the substituted user.

// This only affects data generated by Niddabot and does not affect data provided by DiscordJs. This is not a huge issue as delegating will be used mostly for stuff like debugging.

/**
 * Applies runetime transformations to the message.
 * @param {*} msg Discordjs message object.
 */
module.exports = async msg => {
  const delegate = msg.messageContent.getArgument('delegate')
  if (delegate) msg._delegate = delegate
  else msg._delegate = undefined
}
